version: '3.7'

services:
 
  web:
    container_name: euro2020
    build:
      dockerfile: docker/web.Dockerfile
      context: ../
    volumes:
       - ../app:/app
       - ../locales:/locales       
       - ../data/viz:/data/viz
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host

    env_file:
      - web.env
    networks:
      - euro2020_network
networks:
  euro2020_network:
    driver: bridge
